spring:
  application:
    name: demoweb
  datasource:
    username: root
    password: 
    url: jdbc:mysql://localhost:3306/bd_commercess?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update